# EconomyShop 설정 파일

# 경제 설정
economy:
  starting-balance: 10000  # 신규 플레이어 시작 잔고
  max-balance: 999999999   # 최대 잔고 제한
  currency-symbol: "원"    # 화폐 단위
  allow-negative: false    # 마이너스 잔고 허용 여부

# 상점 설정
shop:
  gui-title: "§6§l━━━━━ 상점 ━━━━━"
  category-title: "§6§l{category} 상점"

  # 메인 메뉴 카테고리
  categories:
    crops:
      name: "§a작물 상점"
      icon: WHEAT
      slot: 11
    minerals:
      name: "§7광물 상점"
      icon: IRON_INGOT
      slot: 13
    special:
      name: "§e특별 아이템"
      icon: DIAMOND
      slot: 15

# 거래 설정
transaction:
  buy-sound: ENTITY_EXPERIENCE_ORB_PICKUP
  sell-sound: ENTITY_VILLAGER_YES
  error-sound: ENTITY_VILLAGER_NO
  confirm-expensive-purchases: true  # 고액 구매시 확인창
  expensive-threshold: 50000         # 고액 기준

# 연동 설정
integrations:
  toolenhancer:
    enabled: true
    items:
      enhancement-stone:
        price: 5000
        stock: -1  # -1 = 무제한

# 메시지
messages:
  prefix: "§6[상점] §f"
  no-permission: "§c권한이 없습니다."
  player-only: "§c플레이어만 사용할 수 있는 명령어입니다."
  player-not-found: "§c플레이어를 찾을 수 없습니다."
  invalid-amount: "§c올바른 금액을 입력해주세요."
  insufficient-balance: "§c잔고가 부족합니다. (필요: {amount}{symbol})"
  purchase-success: "§a{item}§f을(를) §e{amount}개§f 구매했습니다. (§c-{price}{symbol}§f)"
  sell-success: "§a{item}§f을(를) §e{amount}개§f 판매했습니다. (§a+{price}{symbol}§f)"
  transfer-success: "§a{player}§f님께 §e{amount}{symbol}§f을(를) 송금했습니다."
  transfer-received: "§a{player}§f님으로부터 §e{amount}{symbol}§f을(를) 받았습니다."
  balance-check: "§e현재 잔고: §6{balance}{symbol}"
  item-registered: "§a아이템이 상점에 등록되었습니다! §7(ID: {id})"
  item-deleted: "§a아이템이 상점에서 삭제되었습니다."
  no-item-in-hand: "§c손에 아이템을 들고 있어야 합니다."
  shop-is-empty: "§c판매할 아이템이 없습니다."