name: EconomyShop
version: 1.0.3
main: com.krangpq.economyshop.EconomyShop
api-version: '1.20'
author: KrangPQ
description: 독립적인 경제 및 상점 시스템

# 독립성: 다른 플러그인 없이 작동
depend: []

# 호환성: 선택적 연동
softdepend:
  - ToolEnhancer

commands:
  상점:
    description: 상점 메뉴를 엽니다
    aliases: [shop]
    usage: /상점
  돈:
    description: 잔고를 확인합니다
    aliases: [money, bal, balance, 잔고]
    usage: /돈 [플레이어]
  송금:
    description: 다른 플레이어에게 돈을 보냅니다
    aliases: [pay, 지급]
    usage: /송금 <플레이어> <금액>
  경제관리:
    description: 경제 관리 명령어
    aliases: [ecoadmin, ea]
    permission: economyshop.admin
    usage: |
      /경제관리 지급 <플레이어> <금액>
      /경제관리 차감 <플레이어> <금액>
      /경제관리 설정 <플레이어> <금액>
      /경제관리 확인 <플레이어>
  상점등록:
    description: 손에 든 아이템을 상점에 등록합니다
    permission: economyshop.admin
    usage: /상점등록 <가격>
  상점삭제:
    description: 커스텀 아이템을 삭제합니다
    permission: economyshop.admin
    usage: /상점삭제 <아이템ID>

permissions:
  economyshop.admin:
    description: 관리자 권한
    default: op
  economyshop.use:
    description: 상점 사용 권한
    default: true